### ISSUE TITLE
Invalid account when trying to authenticate someone in nested groups

### ISSUE THREAD

**Issue by sneko** [ploxiln/oauth2_proxy#27]
Hi,

I just switched to your repo since it is updated with last PR... I'm in particular interested by authenticating the user against a list of nested groups but I always get this error:

```
403 Permission Denied

Invalid Account

Sign In
````

And when putting the member in the root group it works well. To be more precise, it fails when I tried to put the member in the subgroup directly under the root group. Also, I just have a few members inside (so not limited about 10 pages/request).

Is there anything special to make nested groups working @ploxiln ?

Thank you,

EDIT: "ploxiln/oauth2_proxy:latest" docker image should include the PR about nested groups, no?

EDIT2: in the logs I can see "X not found in any allowed groups", but they are inside... maybe Google groups for checking need specific settings to be readble?

**Comment by ploxiln** [comment]
The "latest" image tag should be of version 2.4.1 which should include https://github.com/ploxiln/oauth2_proxy/pull/6 ... which is based on https://github.com/bitly/oauth2_proxy/pull/500 and which I thought would support nested groups because it looked very similar to https://github.com/bitly/oauth2_proxy/pull/505 ... but now I see that the one I based on did not claim that (and I have not tested this particular provider myself within the last 5 years). Sorry for the misleading feature. I may take a closer look at https://github.com/bitly/oauth2_proxy/pull/505 and see if I can figure out the missing bit ...

**Comment by sneko** [comment]
@ploxiln thanks it would be really great!

Since managing a lot of users can be complicated it would avoid duplicating some work in Google groups :)

**Comment by sneko** [comment]
@ploxiln a possible solution would be to loop over all allowed groups defined through -google-group by the administrator, and recursively get their subgroups to add them to the current allowed groups variable (by checking not already inside).

What do you think?

**Comment by ploxiln** [comment]
If you can just get sub-groups of groups, yes that would be a good way.

Note that #6 changed from getting all members of a group (of which there might easily be hundreds) to getting all groups of a user (of which there is most likely less than 20 or so). So we don't want to iterate over all members of a group ... but if we can just get sub-groups, that would be great. Another workable way would be to look-up a user's groups to see if they are themselves sub-groups (again, better because there's probably far fewer groups than members, for big organizations).

**Comment by sneko** [comment]
I found that:
https://developers.google.com/admin-sdk/directory/v1/reference/members/hasMember

It allows looping on "allowed groups" and knowing if the user is part of those groups or their subgroups. I just tested their online tool to check, it works well.

So pretty efficient since there is N requests for N allowed group.

Do you think that's something you could implement? Otherwise I will try when I will be more confident with Golang :)

**Comment by ploxiln** [comment]
Yes, that's a good way.
I don't know when I'll get around to it, maybe a week or so ... but feel free to make an attempt in the meantime :)

**Comment by sneko** [comment]
@ploxiln I finally took time to dig into Golang to make this tiny improvement: https://github.com/ploxiln/oauth2_proxy/pull/28 

It reduces drastically requests and there is no longer limitation of pagination.

I tested it in "production" with other people and everything is stable and working.

BTW, thanks for maintaining this awesome tool. I hope your fork will become the reference for all contributors ;)
